<!-- Source: http://apogee.online/xml/exer/exercise2/exercise2.html -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Course_Catalog [
<!ELEMENT Chair (Professor)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Course (Title, Description?, Instructors, Prerequisites?)>
<!ATTLIST Course
Number (CS106A | CS106B | CS107 | CS109 | CS124 | CS143 | CS145 | CS221 | CS228 | CS229 | EE108A | EE108B | LING180) #REQUIRED
Enrollment (1070 | 110 | 130 | 180 | 280 | 320 | 500 | 60 | 620 | 90) #IMPLIED
>
<!ELEMENT Prereq (#PCDATA)>
<!ELEMENT Lecturer (First_Name, Middle_Initial?, Last_Name)>
<!ELEMENT Last_Name (#PCDATA)>
<!ELEMENT Professor (First_Name, Middle_Initial?, Last_Name)>
<!ELEMENT Department (Title, Chair, Course+)>
<!ATTLIST Department Code (CS | EE | LING) #REQUIRED>
<!ELEMENT First_Name (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT Instructors ((Lecturer, Professor*) | (Professor+, Lecturer?))>
<!ELEMENT Prerequisites (Prereq+)>
<!ELEMENT Course_Catalog (Department+)>
<!ELEMENT Middle_Initial (#PCDATA)>
]>

<Course_Catalog>
    <Department Code="CS">
        <Title>IT Technologies</Title>
        <Chair>
            <Professor>
                <First_Name>John</First_Name>
                <!--Middle_Initial>F.</Middle_Initial-->
                <Last_Name>Connor</Last_Name>
            </Professor>
        </Chair>
        <Course Number="CS106A" Enrollment="130">
            <Title>Cybernetics</Title>
            <Instructors>
                <Lecturer>
                    <First_Name>Kenny</First_Name>
                    <Last_Name>Perkings</Last_Name>
                </Lecturer>
            </Instructors>
            <Prerequisites>
                <Prereq>Knowledge of terminators</Prereq>
            </Prerequisites>
        </Course>
    </Department>
</Course_Catalog>